webtalk_init -webtalk_dir C:/Users/anton/Desktop/vivado/Progetto ASDI/6-Interfaccia Seriale/esercizio_10/esercizio_10.sim/sim_1/behav/xsim/xsim.dir/tb_Sistema_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 27 15:55:42 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b43462bc-8344-4192-bb1e-80c0228ab4d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "99e6a6a1496e4ab3aedd9b22465665d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "75001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 232340198 -regid "" -xml C:/Users/anton/Desktop/vivado/Progetto ASDI/6-Interfaccia Seriale/esercizio_10/esercizio_10.sim/sim_1/behav/xsim/xsim.dir/tb_Sistema_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/anton/Desktop/vivado/Progetto ASDI/6-Interfaccia Seriale/esercizio_10/esercizio_10.sim/sim_1/behav/xsim/xsim.dir/tb_Sistema_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/anton/Desktop/vivado/Progetto ASDI/6-Interfaccia Seriale/esercizio_10/esercizio_10.sim/sim_1/behav/xsim/xsim.dir/tb_Sistema_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
