#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Feb 27 10:49:35 +0000 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TB_MoltBooth8bit_behav -key {Behavioral:sim_1:Functional:TB_MoltBooth8bit} -tclbatch TB_MoltBooth8bit.tcl -log simulate.log"
xsim TB_MoltBooth8bit_behav -key {Behavioral:sim_1:Functional:TB_MoltBooth8bit} -tclbatch TB_MoltBooth8bit.tcl -log simulate.log

